version: '3.8'

services:
  api-wbd:
    image: 179388324778.dkr.ecr.us-east-2.amazonaws.com/wbd-mais-ages:latest
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      db-wbd:
        condition: service_healthy
    command: sh -c "yarn prisma:migrate:prod && yarn prisma:seed:prod &&  node dist/main.js"
    networks:
      - app-network

  db-wbd:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d wbd_database"]
      interval: 5s
      retries: 5
    volumes:
      - wbd_database:/var/lib/postgresql/data
    networks:
      - app-network

  webserver:
    image: nginx:latest
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - dhparam:/etc/ssl/certs
    depends_on:
      - api-wbd
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    env_file:
      - .env.production
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    entrypoint: /bin/sh
    command: >
      -c "
        sleep 5s  # wait Nginx to boot before challenge;
        certbot certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN} --non-interactive --quiet || true;
        echo 'Starting Certbot renewal loop...';
        while true; do 
          echo 'Running scheduled Certbot renewal check';
          certbot renew --webroot --webroot-path=/var/www/html --quiet;
          sleep 12h;
        done
      "
volumes:
  wbd_database:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ec2-user/app/web-root/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ec2-user/app/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge